name: postprob
description: "PostProb For Post Problem App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  oktoast: ^3.3.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  dotted_border: ^2.1.0
  file_picker: ^8.0.4
  intl: ^0.19.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  lottie: ^3.1.2
  dropdown_button2: ^2.3.9
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
  android_intent_plus: ^5.0.2
  pusher_channels_flutter: ^2.2.1
  flutter_local_notifications: ^17.2.1+2
  firebase_messaging: ^15.0.3
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  rxdart: ^0.28.0
  infinite_scroll_pagination: ^4.0.0
  huge_listview: ^2.0.12
  google_sign_in: ^6.2.1
  permission_handler: ^11.3.1
  dio: ^5.5.0+1
  path_provider: ^2.1.4
  image_gallery_saver: ^2.0.3
  syncfusion_flutter_pdfviewer: ^24.1.43
  video_player: ^2.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/flag/
    - assets/lottie/

  # example:
  fonts:
    - family: DMSans-Bold
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf

    - family: DMSans-Black
      fonts:
        - asset: assets/fonts/DMSans-Black.ttf

    - family: DMSans-Regular
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf

    - family: DMSans-Medium
      fonts:
        - asset: assets/fonts/DMSans-Medium.ttf

    - family: DMSans-Light
      fonts:
        - asset: assets/fonts/DMSans-Light.ttf

    - family: DMSans-SemiBold
      fonts:
        - asset: assets/fonts/DMSans-SemiBold.ttf

    - family: DMSans-Thin
      fonts:
        - asset: assets/fonts/DMSans-Thin.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
